[package]
name = "storage"
version.workspace = true
edition.workspace = true

[dependencies]
types = { path = "../types" }
catalog = { path = "../catalog" }
ast = { path = "../ast" }
chrono = "0.4"

[dev-dependencies]
parser = { path = "../parser" }
